# --- Background & Foreground ---
background            #000000
foreground            #F8F3E0

selection_background  #b11217
selection_foreground  #FFA824

cursor                #D60508
cursor_text_color     #FFA824

# --- Normal colors ---
color0  #0b0b0b   
color1  #b11217 
color2  #c9a227  
color3  #e04a1a   
color4  #2f3f4f   
color5  #6b1a1a   
color6  #3a6f6a   
color7  #e6e2d8  

# --- Bright colors ---
color8  #a1a1a1
color9  #e0181d   
color10 #f4c430   
color11 #ff5a1f   
color12 #4f6b88   
color13 #8c2b2b  
color14 #5fa8a2   
color15 #f9f6ef   

white #F8F3E0
black #000000
bright-red #D60508
dark-red #780804 
bright-yellow #F4B31A 

orange #FF4900
nice-orange #FFA824;

#@define-color 
